version: "3.8"

services:
  db:
    image: postgres:16.4-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: task_management
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
